export const ACTION_TYPES = {
  CHECK_USER:"CHECK_USER",
  SET_PRODUCTS:"SET_PRODUCTS",
  REMOVE_SELECTED_PRODUCT:" REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART:"ADD_TO_CART",
  REMOVE_FROM_CART:"REMOVE_FROM_CART",
  INCREASE_QTY:"INCREASE_QTY",
  DECREASE_QTY:"DECREASE_QTY",
  SORT_BY_PRICE:"SORT_BY_PRICE",
  SEARCH_FILTER:"SEARCH_FILTER",
  CONCURRENT_FETCH:"CONCURRENT_FETCH"
}